### ISSUE TITLE
isDataAvailable not responding correctly?

### ISSUE THREAD

**Issue by drewlarsen** [eladb/Parse-NSCoding#2]
Hi-

First off, thank you for a great library. I'm testing it in a project where I would like to cache a large number of reference objects to disk for later use. Everything seems to be working great, however objects that have been decoded do not return isDataAvailable == YES. This causes some issues in my app and I'm wondering if you've run into this? Is this value not being encoded with the PFObjects?

thank you,
Drew

**Comment by martinrybak** [comment]
Thanks Drew, I'll look into it.

**Comment by martinrybak** [comment]
Drew, I just pushed commit 025b43b31d
See if that resolves the issue for you.

**Comment by martinrybak** [comment]
I just pushed commit 6d901b252b which restores the original isDataAvailable state instead of assuming that isDataAvailable=YES after decoding.

**Comment by drewlarsen** [comment]
Martin, thank you that is great!
I'm curious, what kind of performance you see with archiving this sort of
data?
I've got about 1000 parse objects that don't change very often, so I fetch
them once, and archive to the iphone disk them using your coder. My plan
was to re-fetch them from time-to-time when something changes on the
server.

Problem is, restoring them from disk takes almost 7 secs on my iPhone 5s is
longer than just re-fetching them from Parse!

Have run into similar issues? Did you solve it somehow?

thank you for a great library!

-Drew

On Mon, Mar 24, 2014 at 8:31 AM, martinrybak notifications@github.comwrote:

> Drew, I just pushed commit 025b43bhttps://github.com/updatezen/Parse-NSCoding/commit/025b43b31d
> See if that resolves the issue for you.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/updatezen/Parse-NSCoding/issues/2#issuecomment-38450995
> .

## 

SugarWOD: website http://www.sugarwod.com
free download: iTuneshttps://itunes.apple.com/us/app/sugarwod/id665516348?mt=8
like us: facebook https://www.facebook.com/sugarwod
follow us: twitter https://twitter.com/SugarWOD

**Comment by martinrybak** [comment]
Hm, it works very fast on my end, and for @robbalian who opened ticket #3. Are your objects very large?

**Comment by drewlarsen** [comment]
No, quite small really, a few integers and some short strings.

I'm using:

```
    BOOL success = [NSKeyedArchiver archiveRootObject:ref toFile
```

:@"file/path"];

and:

```
NSDictionary *ref = [NSKeyedUnarchiver unarchiveObjectWithFile
```

:@"file/path"];

are you doing anything different?

On Tue, Mar 25, 2014 at 5:58 PM, martinrybak notifications@github.comwrote:

> Hm, it works very fast on my end, and for @robbalianhttps://github.com/robbalianwho opened ticket
> #3 https://github.com/updatezen/Parse-NSCoding/issues/3. Are your
> objects very large?
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/updatezen/Parse-NSCoding/issues/2#issuecomment-38636162
> .

## 

SugarWOD: website http://www.sugarwod.com
free download: iTuneshttps://itunes.apple.com/us/app/sugarwod/id665516348?mt=8
like us: facebook https://www.facebook.com/sugarwod
follow us: twitter https://twitter.com/SugarWOD

**Comment by martinrybak** [comment]
It's probably slow because you're doing a lot of I/O by archiving to the filesystem for every object. Have you considered using a real caching library? I'm usingTMCache with great success. It can persist to memory or disk.

**Comment by drewlarsen** [comment]
thank you, I'll check it out!

On Thu, Mar 27, 2014 at 10:47 AM, martinrybak notifications@github.comwrote:

> It's probably slow because you're doing a lot of I/O by archiving to the
> filesystem for every object. Have you considered using a real caching
> library? I'm usingTMCache with great success. It can persist to memory or
> disk.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/updatezen/Parse-NSCoding/issues/2#issuecomment-38829357
> .

## 

SugarWOD: website http://www.sugarwod.com
free download: iTuneshttps://itunes.apple.com/us/app/sugarwod/id665516348?mt=8
like us: facebook https://www.facebook.com/sugarwod
follow us: twitter https://twitter.com/SugarWOD
