### ISSUE TITLE
Make library work with non-subclassed PFObjects

### ISSUE THREAD

**Issue by martinrybak** [eladb/Parse-NSCoding#3]

**Comment by martinrybak** [comment]
Pushed commit 6d04819c4b714c6aa756853368c3eceb28276209

**Comment by robbalian** [comment]
This works beautifully! Thank you for the ultra-fast implementation. My feed refreshes so fast with the cache that it uncovered a few other race conditions I hadn't run into before : )

One more question: do you have plans to merge in the work brandonschlenker added to support PFGeoPoint?

Thanks again for your help Martin!

**Comment by martinrybak** [comment]
Great! Yes, I'll add Brandon's code. I saw his pull request but he closed it before I could merge. I'll have to do it manually.
