### ISSUE TITLE
Linker warnings with latest Parse SDK (1.6.2)

### ISSUE THREAD

**Issue by darrensi** [eladb/Parse-NSCoding#30]
I get linker errors when using the library alongside the latest Parse SDK (1.6.2)

ld: warning: instance method 'initWithCoder:' in category from .../libPods-Parse+NSCoding.a(PFACL+NSCoding.o) overrides method from class in .../Pods/Parse/Parse.framework/Parse(PFACL.o)
ld: warning: instance method 'encodeWithCoder:' in category from .../libPods-Parse+NSCoding.a(PFACL+NSCoding.o) overrides method from class in .../Pods/Parse/Parse.framework/Parse(PFACL.o)

Are there any plans to bring this library up to date?
Has anyone forked it and done that?

**Comment by npahucki** [comment]
I fixed this in a pull request months ago that seems to have just been ignored: https://github.com/npahucki/Parse-NSCoding/commit/5c4b4c4db5c11d2b4f77e3f684d2c421b8b578ab

The problem is that the PFACL class now is already serializable and the category provided by the library is no longer needed.

**Comment by darrensi** [comment]
:+1:
