### ISSUE TITLE
PFRelation

### ISSUE THREAD

**Issue by colinhumber** [eladb/Parse-NSCoding#4]
Have you been able to get this working if one of the PFObjects has a PFRelation associated with it? I wrote a simple PFRelation+NSCoding category to serialize the targetClass property, but when the -initWithCoder: tries to deserialize the PFRelation and set it I get an exception:

Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'PFObject values may not have class: PFRelation'

**Comment by martinrybak** [comment]
Hi Colin, sorry for the delay. Currently there is no support for PFRelations. Our company isn't using Parse anymore for many reasons (that's a topic for a future blog post), so we won't be updating this repo any further. However @eladb has agreed to take ownership, so hopefully he or the Github community can work on that further. Cheers!

**Comment by ace1294** [comment]
Colin did you ever get your extension for PFRelation working? If not I bet we can collaborate.

**Comment by thibautrey** [comment]
Ok guys I also need to work with PFRelation so I will give it try. Hopefully I will be back in a few hours with the implementation. If someone has already started some work on it feel free to spread it.

**Comment by zake1989** [comment]
Hi guys, anyone resolve this problem I also got this 
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'PFObject values may not have class: PFRelation'
don't even know where this problem came from~~

**Comment by LJWilliamsIV** [comment]
I'm having the same issue. @zake1989  have you found a solution yet?
