### ISSUE TITLE
Add support for PFGeoPoint+NSCoding 

### ISSUE THREAD

**Issue by nbrambilla** [eladb/Parse-NSCoding#5]
Hi,

I include "pod 'Parse+NSCoding', '~> 0.1.3'" in podfile and execute "pod install" but not appears in the project the PFGeoPoint+NSCoding files.

I hope that someone make me a solution

Thanx!!!

**Comment by martinrybak** [comment]
I will add PFGeoPoint encoding soon!

**Comment by ipedro** [comment]
hey, just wrote a PFGeoPoint+NSCoding based on what you already did, hope it helps! 
http://cl.ly/2K1S2f3q0y3f

Very nice work btw! thx a lot

**Comment by martinrybak** [comment]
Thanks @ipedro! I added your PFGeoPoint+NSCoding files.
