### ISSUE TITLE
Parse warning

### ISSUE THREAD

**Issue by chrisharrison** [eladb/Parse-NSCoding#7]
When using this library I get the following in the output:

`Warning: A long-running Parse operation is being executed on the main thread. Break on warnParseOperationOnMainThread() to debug.`

Any idea what this is about?

**Comment by martinrybak** [comment]
Are you performing a fetch or lazy load of any sort?

**Comment by martinrybak** [comment]
Have you tried putting a debug breakpoint on warnParseOperationOnMainThread() for more information?
